classdef tsgqc < handle
  %TSGQC: Thermosalinograph (TSG) Quality Control software
  
  %   %% COPYRIGHT & LICENSE
  %  Copyright 2007 - IRD US191, all rights reserved.
  %
  %  This file is part of tsgqc.
  %
  %    TSGQC is free software; you can redistribute it and/or modify
  %    it under the terms of the GNU General Public License as publDisplayished by
  %    the Free Software Foundation; either version 2 of the License, or
  %    (at your option) any later version.
  %
  %    tsgqc is distributed in the hope that it will be useful,
  %    but WITHOUT ANY WARRANTY; without even the implied warranty of
  %    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  %    GNU General Public License for more details.
  %
  %    You should have received a copy of the GNU General Public License
  %    along with Datagui; if not, write to the Free Software
  %    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
  
  properties
    hdlMainFig
    hdlFileMenu
    hdlOpenMenu
    hdlSaveMenu
    hdlExportMenu
    hdlExportTsg
    hdlExportSample
    hdlQuitMenu
    hdlInfoPanel
    hdlInfoFileText
    hdlInfoDateText
    hdlInfoSSPSText
    hdlInfoSSJTText
    hdlInfoSSTPText
    hdlInfoLatText
    hdlInfoLongText
    hdlToolbar
    hdlOpenPushtool
    hdlSavePushtool
    hdlPrintFigPushtool
    hdlZoomInToggletool
    hdlZoomOutToggletool
    hdlPanToggletool
    hdlQCToggletool
    hdlTimelimitToggletool
    hdlMapToggletool
    hdlGoogleEarthPushtool
    hdlClimToggletool
    hdlCalToggletool
    hdlInterpToggletool
    hdlBottleToggletool
    hdlHeaderPushtool
    hdlReportPushtool
    hdlPlotsPanel
    hdlPlotAxes
    hdlMapFig
    
    nc
    inputFile
    outputFile
    preference = preference
    path
    configFile
    display
    help
    
    fileListenerHdl
    fontSize = 11
  end
  
  events
    fileopen
    fileclose
    axesVisible
  end
  
  methods
    
    % constructor
    % -----------
    function obj = tsgqc(varargin)
      property_argin = varargin(1:end);
      while length(property_argin) >= 2
        property = property_argin{1};
        value    = property_argin{2};
        property_argin = property_argin(3:end);
        switch lower(property)
          case {'inputfile', 'input'}
            obj.inputFile = value;
          case {'outputfile', 'output'}
            obj.outputFile = value;
          case 'display'
            obj.display = value;
          case 'help'
            obj.help = value;
          otherwise
            error('Unknow property: "%s"', property);
        end
      end
      obj.path = mfilename('fullpath');
      obj.configFile = [prefdir, filesep, mfilename, '.mat'];
      obj.setMainUI;
      obj.setDisplayUI;
      obj.setToolBarUI;
      obj.setAxesUI
      
      % add listener
      obj.fileListenerHdl = addlistener(obj,'fileopen',@obj.fileEvnt);
    end
    
    % destructor
    % ----------
    function delete(obj)
      % method save_config
      saveConfig(obj);
      closereq;
    end
    
    function setMainUI(obj)
      
      % Create and then hide the GUI as it is being constructed.
      handleVisibility = 'on';
      
      % Screen limits for the GUI
      r = groot;
      r.Units = 'normalized';
      guiLimits = r.ScreenSize;
      guiLimits(1) = guiLimits(1) + 0.01;
      guiLimits(2) = guiLimits(2) + 0.05;
      guiLimits(3) = guiLimits(3) - 0.02;
      guiLimits(4) = guiLimits(4) - 0.15;
      
      obj.hdlMainFig = figure(...
        'Name', 'TSG Validation', ...
        'NumberTitle', 'off', ...
        'Resize', 'on', ...
        'Menubar', 'none', ...
        'Toolbar', 'none', ...
        'UserData', 'ButtonMotionOff', ...
        'HandleVisibility', handleVisibility,...
        'Visible','on',...
        'Tag','TAG_TSG-QC_GUI',...
        'Units', 'normalized',...
        'Position',guiLimits, ...
        'Color', get( 0, 'DefaultUIControlBackgroundColor' ),...
        'CloseRequestFcn', {@(src,evt) delete(obj)});
      % 'WindowButtonMotionFcn', {@(src,evt) mouseMotion(obj,src)}, ...
      
      %  Menu File
      %   -----------------------------------------------------------------------
      obj.hdlFileMenu = uimenu(...
        'Parent', obj.hdlMainFig,...
        'HandleVisibility', handleVisibility,...
        'Label', 'File');
      
      obj.hdlOpenMenu = uimenu(...
        'Parent', obj.hdlFileMenu,...
        'Label','Open',...
        'Accelerator','O',...
        'HandleVisibility', handleVisibility,...
        'UserData', 'off',...
        'Callback', {@(src,evt) openMenu(obj,src)});
      
      obj.hdlSaveMenu = uimenu(...
        'Parent', obj.hdlFileMenu,...
        'Label','Save',...
        'Accelerator','S',...
        'Enable', 'off',...
        'UserData', 'off',...
        'HandleVisibility', handleVisibility,...
        'Callback', {@(src,evt) saveMenu(obj,src)});
      
      obj.hdlExportMenu = uimenu(...
        'Parent', obj.hdlFileMenu,...
        'Label','Export',...
        'Accelerator','E',...
        'Enable', 'off',...
        'UserData', 'off',...
        'HandleVisibility', handleVisibility,...
        'Callback', {@(src,evt) exportMenu(obj,src)});
      
      obj.hdlExportTsg = uimenu(...
        'Parent', obj.hdlFileMenu,...
        'Label','Tsg ascii file',...
        'Enable', 'off',...
        'HandleVisibility', handleVisibility,...
        'Callback', {@(src,evt) exportTsg(obj,src)});
      
      obj.hdlExportSample = uimenu(...
        'Parent', obj.hdlFileMenu,...
        'Label','Sample ascii file',...
        'Enable', 'off',...
        'HandleVisibility', handleVisibility,...
        'Callback',{@(src,evt) exportSample(obj,src)});
      
      obj.hdlQuitMenu = uimenu(...
        'Parent',obj.hdlFileMenu,...
        'Label','Quit',...
        'Separator','on',...
        'Accelerator','Q',...
        'HandleVisibility', handleVisibility,...
        'Callback',{@(src,evt) delete(obj)});
      
    end % end of setMainUI
    
    function setDisplayUI(obj)
      
      %  Dynamic text area that displays the loaded filename, date, position and
      %  salinity, temperature
      %  ------------------------------------------------------------------------
      
      % Create an uipanel
      % -----------------
      obj.hdlInfoPanel = uipanel( ...
        'Parent', obj.hdlMainFig, ...
        'Units', 'normalized', ...
        'BorderType', 'none',...
        'Visible', 'on', ...
        'Position',[.01, .96, .98, .04]);
      
      % Dynamic text area that displays the date
      % ----------------------------------------
      uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Units', 'normalized', ...
        'Style', 'Text', ...
        'Fontsize', obj.fontSize, ...
        'Fontweight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'Position',[.01, .25, .04, .6], ...
        'String', 'File:');
      obj.hdlInfoFileText = uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Style', 'text', ...
        'Fontsize', obj.fontSize, ...
        'Visible','on',...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left', ...
        'String', 'No file loaded', ...
        'Position', [.05, .25, .1, .6]);
      
      % Text area that displays the date
      % --------------------------------
      uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Units', 'normalized', ...
        'Style', 'Text', ...
        'Fontsize', obj.fontSize, ...
        'Fontweight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'Position',[.15, .25, .04, .6], ...
        'String', 'Date:');
      obj.hdlInfoDateText = uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Style', 'text', ...
        'Fontsize', obj.fontSize, ...
        'Visible','on',...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left', ...
        'String', 'N/A', ...
        'Position', [.20, .25, .13, .6]);
      
      % Text area that displays the latitude
      % ------------------------------------
      uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Units', 'normalized', ...
        'Style', 'Text', ...
        'Fontsize', obj.fontSize, ...
        'Fontweight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'Position',[.33, .25, .06, .6], ...
        'String', 'Latitude:');
      obj.hdlInfoLatText = uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Style', 'text', ...
        'Fontsize', obj.fontSize, ...
        'Visible','on',...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left', ...
        'String', 'N/A', ...
        'Position', [.4, .25, .9, .6]);
      
      % Text area that displays the longitude
      % -------------------------------------
      uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Units', 'normalized', ...
        'Style', 'Text', ...
        'Fontsize', obj.fontSize, ...
        'Fontweight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'Position',[.495, .25, .08, .6], ...
        'String', 'Longitude:');
      obj.hdlInfoLongText = uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Style', 'text', ...
        'Fontsize', obj.fontSize, ...
        'Visible','on',...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left', ...
        'String', 'N/A', ...
        'Position', [.585, .25, .09, .6]);
      
      % Text area that display salinity and temperature
      % -----------------------------------------------
      uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Units', 'normalized', ...
        'Style', 'Text', ...
        'Fontsize', obj.fontSize, ...
        'Fontweight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'Position', [.68, .25, .05, .6], ...
        'String', 'SSPS:');
      obj.hdlInfoSSPSText = uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Style', 'text', ...
        'Fontsize', obj.fontSize, ...
        'Visible','on',...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left', ...
        'String', 'N/A', ...
        'Position', [.73, .25, .05, .6]);
      uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Units', 'normalized', ...
        'Style', 'Text', ...
        'Fontsize', obj.fontSize, ...
        'Fontweight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'Position',[.785, .25, .05, .6], ...
        'String', 'SSJT:');
      obj.hdlInfoSSJTText = uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Style', 'text', ...
        'Fontsize', obj.fontSize, ...
        'Visible','on',...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left', ...
        'String', 'N/A', ...
        'Position', [.835, .25, .05, .6]);
      uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Units', 'normalized', ...
        'Style', 'Text', ...
        'Fontsize', obj.fontSize, ...
        'Fontweight', 'bold', ...
        'HorizontalAlignment', 'left', ...
        'Position',[.89, .25, .05, .6], ...
        'String', 'SSTP:');
      obj.hdlInfoSSTPText = uicontrol(...
        'Parent', obj.hdlInfoPanel, ...
        'Style', 'text', ...
        'Fontsize', obj.fontSize, ...
        'Visible','on',...
        'Units', 'normalized',...
        'HorizontalAlignment', 'left', ...
        'String', 'N/A', ...
        'Position', [.94, .25, .05, .6]);
    end % end of setDisplayUI
    
    function setToolBarUI(obj)
      obj.hdlToolbar       =   uitoolbar(...   % Toolbar for Open and Print buttons
        'Parent',obj.hdlMainFig, ...
        'HandleVisibility','on');
      
      obj.hdlOpenPushtool  =   uipushtool(...   % Opendoc toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Open file',...
        'CData', tsgqc.read('opendoc.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_OPEN',...
        'UserData', 'off',...
        'Enable', 'on',...
        'ClickedCallback', {@(src,evt) openMenu(obj,src)});
      
      obj.hdlSavePushtool  =   uipushtool(...   % Open Save toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Save NetCDF file',...
        'CData', tsgqc.read('savedoc.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_SAVE',...
        'Enable', 'off',...
        'ClickedCallback', @SaveMenuCallback);
      
      obj.hdlPrintFigPushtool  =   uipushtool(...   % Open Save toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Print figures',...
        'CData', tsgqc.read('printdoc.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_PRINTFIG',...
        'visible', 'on', 'Enable', 'on',...
        'ClickedCallback', @PrintFigMenuCallback);
      
      obj.hdlZoomInToggletool = uitoggletool(...   % Open Zoom In (increase) toolbar button
        'Parent',obj.hdlToolbar,...
        'Separator', 'on', ...
        'TooltipString','Zoom In (increase)',...
        'CData', tsgqc.read('zoomplus.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_ZOOM_IN',...
        'OnCallback',  @ZoomIn_OnMenuCallback,...
        'OffCallback',  @ZoomIn_OffMenuCallback);
      
      obj.hdlZoomOutToggletool = uitoggletool(...   % Open Zoom Out (decrease) toolbar button
        'Parent',obj.hdlToolbar,...
        'Separator', 'on', ...
        'TooltipString','Zoom Out (decrease)',...
        'CData', tsgqc.read('zoomminus.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_ZOOM_OUT',...
        'OnCallback',  @ZoomOut_OnMenuCallback,...
        'OffCallback',  @ZoomOut_OffMenuCallback);
      
      obj.hdlPanToggletool  =   uitoggletool(...   % Open Pan toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Pan',...
        'CData', tsgqc.read('pan.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_PAN',...
        'Enable', 'off',...
        'OffCallback', @Pan_OffMenuCallback,...
        'OnCallback',  @Pan_OnMenuCallback);
      
      obj.hdlQCToggletool  =   uitoggletool(...   % Open QC toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Validation codes',...
        'Separator', 'on', ...
        'CData', tsgqc.read('qcicon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_QC',...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', @QC_OffMenuCallback,...
        'OnCallback',  @QC_OnMenuCallback);
      
      obj.hdlTimelimitToggletool  = uitoggletool(...
        'Parent',obj.hdlToolbar,...
        'TooltipString','Select time limit',...
        'CData', tsgqc.read('selecttime.mat'),...
        'HandleVisibility','on', ...
        'Tag', 'CORRECT_STARTTIME', ...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', @SelectTime_OffMenuCallback,...
        'OnCallback',  @SelectTime_OnMenuCallback);
      
      obj.hdlMapToggletool  =   uitoggletool(...   % Open Map toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Display ship track with m_map',...
        'Separator', 'on', ...
        'CData', tsgqc.read('mapicon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_MAP',...
        'UserData', 'off', ...
        'Enable', 'off',...
        'OffCallback', {@(src,evt) Map_OffMenuCallback(obj,src)},...
        'OnCallback',  {@(src,evt) Map_OnMenuCallback(obj,src)});
      
      obj.hdlGoogleEarthPushtool  = uipushtool(...   % Open Google Earth and plot track
        'Parent',obj.hdlToolbar,...
        'TooltipString','Display ship track with Google Earth',...
        'CData', tsgqc.read('google_earth.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_GOOGLEARTH',...
        'Enable', 'off',...
        'ClickedCallback', @GoogleEarthMenuCallback);
      
      obj.hdlClimToggletool  =   uitoggletool(...   % Open Climatology toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Climatology',...
        'CData', tsgqc.read('climicon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_CLIM',...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', @Clim_OffMenuCallback,...
        'OnCallback',  @Clim_OnMenuCallback);
      
      obj.hdlCalToggletool  =   uitoggletool(...   %
        'Parent',obj.hdlToolbar,...
        'TooltipString','Calibration sensors',...
        'Separator', 'on', ...
        'CData', tsgqc.read('outils.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_CAL',...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', @Cal_OffMenuCallback,...
        'OnCallback',  @Cal_OnMenuCallback);
      
      obj.hdlInterpToggletool  =   uitoggletool(...   %
        'Parent',obj.hdlToolbar,...
        'TooltipString','Interpolate missing position',...
        'CData', tsgqc.read('interp.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_INTERP',...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', @Inter_OffMenuCallback,...
        'OnCallback',  @Inter_OnMenuCallback);
      
      obj.hdlBottleToggletool  = uitoggletool(...   % Correction module toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Correct the SSS TSG data',...
        'CData', tsgqc.read('bottleicon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_BOTTLE',...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', @Bottle_OffMenuCallback,...
        'OnCallback',  @Bottle_OnMenuCallback);
      
      obj.hdlHeaderPushtool  = uipushtool(...   % Open headerForm button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Fill the header form',...
        'Separator', 'on', ...
        'CData', tsgqc.read('hdricon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_HEADER',...
        'Enable', 'off',...
        'ClickedCallback', @HeaderMenuCallback);
      
      obj.hdlReportPushtool  = uipushtool(...   % Open Report saving button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Save a report',...
        'CData', tsgqc.read('reporticon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_REPORT',...
        'Enable', 'off',...
        'ClickedCallback', @ReportMenuCallback);
      
    end % end of setToolBarUI
    
    function setAxesUI(obj)
      obj.hdlPlotsPanel = uipanel( ...
        'Parent', obj.hdlMainFig, ...
        'Units', 'normalized', ...
        'BorderType', 'etchedin',...
        'Visible', 'on',...
        'Position',[0.15, 0.0, .85, .95]);
      
      obj.hdlPlotAxes(1) = axes( 'Parent', obj.hdlPlotsPanel, 'Visible', 'off', ...
        'box', 'on', 'Units', 'normalized','Tag', 'TAG_AXES_1', ...
        'HandleVisibility','on', 'Position',[.05, .64, .93, .35]);
      obj.hdlPlotAxes(2) = axes( 'Parent', obj.hdlPlotsPanel, 'Visible', 'off',...
        'box', 'on', 'Units', 'normalized', 'Tag', 'TAG_AXES_2', ...
        'HandleVisibility','on', 'Position',[.05, .33, .93, .27]);
      obj.hdlPlotAxes(3) = axes('Parent', obj.hdlPlotsPanel, 'Visible', 'off',...
        'box', 'on', 'Units', 'normalized', 'Tag', 'TAG_AXES_3', ...
        'HandleVisibility','on', 'Position',[.05, .02, .93, .27]);
      
      % The map will be plot  a new figure
      obj.hdlMapFig = figure(...
        'BackingStore','off',...
        'Name', 'TSG SHIP TRACK', ...
        'NumberTitle', 'off', ...
        'Resize', 'on', ...
        'Menubar','figure', ...
        'Toolbar', 'none', ...
        'Tag', 'MAP_FIGURE', ...
        'Visible','off',...
        'WindowStyle', 'normal', ...
        'CloseRequestFcn', @QuitMapCallback,...
        'Units', 'normalized',...
        'Position',[0.17, 0.05, .8, .44],...
        'Color', get(0, 'DefaultUIControlBackgroundColor'));
      
      obj.hdlPlotAxes(4) = axes(...     % the axes for plotting ship track map
        'Parent', obj.hdlMapFig, ...
        'Units', 'normalized', ...
        'Visible', 'off', ...
        'Tag', 'TAG_AXES_MAP', ...
        'Color', 'none', ...
        'UserData', 'off', ...
        'HandleVisibility','on', ...
        'Position',[.05, .05, .9, .9]);
      
    end % end of setAxesUI
    
    % callbacks
    % ---------
    function saveConfig(obj, ~)
      disp(strcat(class(obj),': save callback module not yet implemented', 'modal'));
    end % end of saveConfig
    
    function openMenu(obj, ~)
      [theFileName, thePathName] = uigetfile(...
        {'*.nc;*.cdf','NetCDF (*.nc,*.cdf)'}, 'Select file');
      if isequal(theFileName,0) || isequal(thePathName,0)
        disp('User pressed cancel')
      else
        disp(['User selected ', fullfile(thePathName, theFileName)])
        obj.nc = tsgqc.netcdf(fullfile(thePathName, theFileName));
        notify(obj, 'fileopen');
      end
      
    end % end of openMenu
    
    function Map_OnMenuCallback(obj, ~)
      
      % Desactivate Zoom and Pan toggle buttons
      set(obj.hdlZoomInToggletool,  'state', 'off' );
      set(obj.hdlZoomOutToggletool,  'state', 'off' );
      set(obj.hdlPanToggletool,   'state', 'off' );
      
      % Make the earth map visible
      set(obj.hdlMapFig, 'Visible', 'on' );
      
      %erase_Line( obj.hdlPlotAxes, 4 );     
      %plot_map( hMainFig, hPlotAxes)
      
      % De-activate keyPressFcn callback on main fig
      set(obj.hdlMainFig, 'KeyPressFcn', []);
      
    end
    
    function Map_OffMenuCallback(obj, ~)
      
      % Make the earth map invisible
      set(obj.hdlMapFig, 'Visible', 'off' );
      
      % Re-activate keyPressFcn callback on main fig
      set(obj.hdlMainFig, 'KeyPressFcn', @keyPressFcnCallback);
      
    end
    
    function exportMenu(obj, ~)
      disp(strcat(class(obj),': exportMenu callback module not yet implemented', 'modal'));
    end % end of exportMenu
    
    function exportTsg(obj, ~)
      disp(strcat(class(obj),': exportTsg callback module not yet implemented', 'modal'));
    end % end of exportTsg
    
    function exportSample(obj, ~)
      disp(strcat(class(obj),': exportSample callback module not yet implemented', 'modal'));
    end % end of exportSample
    
    function mouseMotion(obj, ~)
      msgbox(strcat(class(obj),': mouseMotion callback module not yet implemented', 'modal'));
    end
    
  end % end of public methods
  
  methods (Access = private)
    
    % wait for dataAvalaible event from CTD
    function fileEvnt(obj,~,~)
      set(obj.hdlSaveMenu,  'Enable', 'on');
      set(obj.hdlExportMenu,  'Enable', 'on');
      set(obj.hdlSavePushtool,  'Enable', 'on');
      set(obj.hdlPrintFigPushtool,  'Enable', 'on');
      set(obj.hdlZoomInToggletool,  'Enable', 'on');
      set(obj.hdlZoomOutToggletool,  'Enable', 'on');
      set(obj.hdlPanToggletool,  'Enable', 'on');
      set(obj.hdlQCToggletool,  'Enable', 'on');
      set(obj.hdlTimelimitToggletool,  'Enable', 'on');
      set(obj.hdlMapToggletool,  'Enable', 'on');
      set(obj.hdlGoogleEarthPushtool,  'Enable', 'on');
      set(obj.hdlClimToggletool,  'Enable', 'on');
      set(obj.hdlCalToggletool,  'Enable', 'on');
      set(obj.hdlInterpToggletool,  'Enable', 'on');
      set(obj.hdlBottleToggletool,  'Enable', 'on');
      set(obj.hdlHeaderPushtool,  'Enable', 'on');
      set(obj.hdlReportPushtool,  'Enable', 'on');
    end
    
  end % end of private methods
  
  methods(Static)
    
    function cdata = read(filename)
      thePath = fileparts(which(mfilename));
      data = load(strcat(thePath,filesep,'icons',filesep,filename));
      cdata = data.cdata;
    end
    
  end % end of static methods
end

