function setLeftUI(obj)
% setLeftUI draw a panel with popupmenu to select parameters

% choose parameters (SSPS - SSTP - SSJT)
obj.hdlLeftPanel  = uibuttongroup(...
  'Parent', obj.hdlMainFig, ...
  'Title', 'TSG Parameter', ...
  'FontSize', obj.preference.fontSize, 'Fontweight', 'bold', ...
  'tag', 'TAG_PARA_DISPLAY_PANEL',...
  'HandleVisibility','on',...
  'Visible', 'off',...
  'BorderType', 'etchedin',...
  'Units', 'normalized', 'Position', [.0, .78, .15, .18]);

text= {'Validation - Top'; 'Middle plot'; 'Bottom plot'};
ybottom = [.7 .38 .05];

% set popup menu for available parameters, string is equal to NONE first
for ipmh = 1 : 3
  obj.hdlParameter(ipmh) = uicontrol(...
    'Parent', obj.hdlLeftPanel , 'Style', 'popupmenu', ...
    'String', { 'NONE' }, 'Value', 1, ...
    'HandleVisibility', 'on', ...
    'Callback', @(src,evnt)parameterChoiceCallback(src,evnt,obj), ...
    'Units', 'normalized', 'Position', [.01, ybottom(ipmh), .3, 0.25]);
  
  obj.hdlParameterText(ipmh) = uicontrol( ...
    'Parent', obj.hdlLeftPanel , 'Style', 'Text', ...
    'String', text{ipmh}, ...
    'HorizontalAlignment', 'left', 'FontSize', obj.preference.fontSize-1, ...
    'Units', 'normalized',  'Position',[.35, ybottom(ipmh), .6, 0.25]);
end

  % nested function
  % parameterChoiceEventData send a signal to plot data again   
  % -----------------
  function parameterChoiceCallback(~, ~, obj)
    
    % get cell array of parameters
    para1 = get(obj.hdlParameter(1), 'string');
    para2 = get(obj.hdlParameter(2), 'string');
    para3 = get(obj.hdlParameter(3), 'string');
    
    % build a cell array of selected parameters
    PARA = {para1{get(obj.hdlParameter(1), 'value')}, ...
      para2{get(obj.hdlParameter(2), 'value')},...
      para3{get(obj.hdlParameter(3), 'value')}};
    
    % pass cell array PARA to evtData instance of parameterChoiceEventData
    % object which inherit from eventData class
    evtData = tsgqc.parameterChoiceEventData(PARA);
    
    % send an event with evtData as argument (evtData.param = PARA)
    notify(obj,'dataAvailable', evtData)
  end

end

