function setLeftUI(obj)

%  Choose parameters (SSPS - SSTP - SSJT)
obj.hdlLeftPanel  = uibuttongroup(...
  'Parent', obj.hdlMainFig, ...
  'Title', 'TSG Parameter', ...
  'FontSize', obj.preference.fontSize, 'Fontweight', 'bold', ...
  'tag', 'TAG_PARA_DISPLAY_PANEL',...
  'HandleVisibility','on',...
  'Visible', 'off',...
  'BorderType', 'etchedin',...
  'Units', 'normalized', 'Position', [.0, .78, .15, .18]);

text= {'Validation - Top'; 'Middle plot'; 'Bottom plot'};
ybottom = [.7 .38 .05];
for ipmh= 1 : 3
 obj.hdlParameter(ipmh) = uicontrol(...
    'Parent', obj.hdlLeftPanel , 'Style', 'popupmenu', ...
    'String', { 'NONE' }, 'Value', 1, ...
    'HandleVisibility', 'on', ...
    'Callback', @obj.parameterChoice, ...
    'Units', 'normalized', 'Position', [.01, ybottom(ipmh), .3, 0.25]);
  obj.hdlParameterText(ipmh) = uicontrol( ...
    'Parent', obj.hdlLeftPanel , 'Style', 'Text', ...
    'String', text{ipmh}, ...
    'HorizontalAlignment', 'left', 'FontSize', obj.preference.fontSize-1, ...
    'Units', 'normalized',  'Position',[.35, ybottom(ipmh), .6, 0.25]);
end
