 function setMainUI(obj)
      
      % Create and then hide the GUI as it is being constructed.
      handleVisibility = 'on';
      
      % Screen limits for the GUI
      r = groot;
      r.Units = 'normalized';
      guiLimits = r.ScreenSize;
      guiLimits(1) = guiLimits(1) + 0.01;
      guiLimits(2) = guiLimits(2) + 0.05;
      guiLimits(3) = guiLimits(3) - 0.02;
      guiLimits(4) = guiLimits(4) - 0.15;
      
      obj.hdlMainFig = figure(...
        'Name', 'TSG Validation', ...
        'NumberTitle', 'off', ...
        'Resize', 'on', ...
        'Menubar', 'none', ...
        'Toolbar', 'none', ...
        'UserData', 'ButtonMotionOff', ...
        'HandleVisibility', handleVisibility,...
        'Visible','on',...
        'Tag','TAG_TSG-QC_GUI',...
        'Units', 'normalized',...
        'Position',guiLimits, ...
        'Color', get( 0, 'DefaultUIControlBackgroundColor' ),...
        'CloseRequestFcn', {@(src,evt) delete(obj)});
      % 'WindowButtonMotionFcn', {@(src,evt) mouseMotion(obj,src)}, ...
      
      %  Menu File
      %   -----------------------------------------------------------------------
      obj.hdlFileMenu = uimenu(...
        'Parent', obj.hdlMainFig,...
        'HandleVisibility', handleVisibility,...
        'Label', 'File');
      
      obj.hdlOpenMenu = uimenu(...
        'Parent', obj.hdlFileMenu,...
        'Label','Open',...
        'Accelerator','O',...
        'HandleVisibility', handleVisibility,...
        'UserData', 'off',...
        'Callback', {@(src,evt) openMenuCallback(obj,src)});
      
      obj.hdlSaveMenu = uimenu(...
        'Parent', obj.hdlFileMenu,...
        'Label','Save',...
        'Accelerator','S',...
        'Enable', 'off',...
        'UserData', 'off',...
        'HandleVisibility', handleVisibility,...
        'Callback', {@(src,evt) saveMenuCallback(obj,src)});
      
      obj.hdlExportMenu = uimenu(...
        'Parent', obj.hdlFileMenu,...
        'Label','Export',...
        'Accelerator','E',...
        'Enable', 'off',...
        'UserData', 'off',...
        'HandleVisibility', handleVisibility,...
        'Callback', {@(src,evt) exportMenuCallback(obj,src)});
      
      obj.hdlExportTsg = uimenu(...
        'Parent', obj.hdlFileMenu,...
        'Label','Tsg ascii file',...
        'Enable', 'off',...
        'HandleVisibility', handleVisibility,...
        'Callback', {@(src,evt) exportTsgCallback(obj,src)});
      
      obj.hdlExportSample = uimenu(...
        'Parent', obj.hdlFileMenu,...
        'Label','Sample ascii file',...
        'Enable', 'off',...
        'HandleVisibility', handleVisibility,...
        'Callback',{@(src,evt) exportSampleCallback(obj,src)});
      
      obj.hdlQuitMenu = uimenu(...
        'Parent',obj.hdlFileMenu,...
        'Label','Quit',...
        'Separator','on',...
        'Accelerator','Q',...
        'HandleVisibility', handleVisibility,...
        'Callback',{@(src,evt) delete(obj)});
      
    end % end of setMainUI