  function setToolBarUI(obj)
      obj.hdlToolbar       =   uitoolbar(...   % Toolbar for Open and Print buttons
        'Parent',obj.hdlMainFig, ...
        'HandleVisibility','on');
      
      obj.hdlOpenPushtool  =   uipushtool(...   % Opendoc toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Open file',...
        'CData', tsgqc.readIcon('opendoc.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_OPEN',...
        'UserData', 'off',...
        'Enable', 'on',...
        'ClickedCallback', {@(src,evt) openMenuCallback(obj,src)});
      
      obj.hdlSavePushtool  =   uipushtool(...   % Open Save toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Save NetCDF file',...
        'CData', tsgqc.readIcon('savedoc.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_SAVE',...
        'Enable', 'off',...
        'ClickedCallback', {@(src,evt) saveMenuCallback(obj,src)});
      
      obj.hdlPrintFigPushtool  =   uipushtool(...   % Open Save toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Print figures',...
        'CData', tsgqc.readIcon('printdoc.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_PRINTFIG',...
        'visible', 'on', 'Enable', 'on',...
        'ClickedCallback', {@(src,evt) printFigMenuCallback(obj,src)});
      
      obj.hdlZoomInToggletool = uitoggletool(...   % Open Zoom In (increase) toolbar button
        'Parent',obj.hdlToolbar,...
        'Separator', 'on', ...
        'TooltipString','Zoom In (increase)',...
        'CData', tsgqc.readIcon('zoomplus.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_ZOOM_IN',...
        'OnCallback',  {@(src,evt) zoomInOnMenuCallback(obj,src)},...
        'OffCallback',  {@(src,evt) zoomInOffMenuCallback(obj,src)});
      
      obj.hdlZoomOutToggletool = uitoggletool(...   % Open Zoom Out (decrease) toolbar button
        'Parent',obj.hdlToolbar,...
        'Separator', 'on', ...
        'TooltipString','Zoom Out (decrease)',...
        'CData', tsgqc.readIcon('zoomminus.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_ZOOM_OUT',...
        'OnCallback',  {@(src,evt) zoomOutOnMenuCallback(obj,src)},...
        'OffCallback',  {@(src,evt) zoomOutOffMenuCallback(obj,src)});
      
      obj.hdlPanToggletool  =   uitoggletool(...   % Open Pan toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Pan',...
        'CData', tsgqc.readIcon('pan.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_PAN',...
        'Enable', 'off',...
        'OffCallback', {@(src,evt) panOffMenuCallback(obj,src)},...
        'OnCallback',  {@(src,evt) panOnMenuCallback(obj,src)});
      
      obj.hdlQCToggletool  =   uitoggletool(...   % Open QC toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Validation codes',...
        'Separator', 'on', ...
        'CData', tsgqc.readIcon('qcicon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_QC',...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', {@(src,evt) qcOffMenuCallback(obj,src)},...
        'OnCallback',  {@(src,evt) qcOnMenuCallback(obj,src)});
      
      obj.hdlTimelimitToggletool  = uitoggletool(...
        'Parent',obj.hdlToolbar,...
        'TooltipString','Select time limit',...
        'CData', tsgqc.readIcon('selecttime.mat'),...
        'HandleVisibility','on', ...
        'Tag', 'CORRECT_STARTTIME', ...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', {@(src,evt) selectTimeOffMenuCallback(obj,src)},...
        'OnCallback',  {@(src,evt) selectTimeOnMenuCallback(obj,src)});
      
      obj.hdlMapToggletool  =   uitoggletool(...   % Open Map toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Display ship track with m_map',...
        'Separator', 'on', ...
        'CData', tsgqc.readIcon('mapicon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_MAP',...
        'UserData', 'off', ...
        'Enable', 'off',...
        'OffCallback', {@(src,evt) mapOffMenuCallback(obj,src)},...
        'OnCallback',  {@(src,evt) mapOnMenuCallback(obj,src)});
      
      obj.hdlGoogleEarthPushtool  = uipushtool(...   % Open Google Earth and plot track
        'Parent',obj.hdlToolbar,...
        'TooltipString','Display ship track with Google Earth',...
        'CData', tsgqc.readIcon('google_earth.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_GOOGLEARTH',...
        'Enable', 'off',...
        'ClickedCallback', {@(src,evt) googleEarthMenuCallback(obj,src)});
      
      obj.hdlClimToggletool  =   uitoggletool(...   % Open Climatology toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Climatology',...
        'CData', tsgqc.readIcon('climicon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_CLIM',...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', {@(src,evt) climOffMenuCallback(obj,src)},...
        'OnCallback',  {@(src,evt) climOnMenuCallback(obj,src)});
      
      obj.hdlCalToggletool  =   uitoggletool(...   %
        'Parent',obj.hdlToolbar,...
        'TooltipString','Calibration sensors',...
        'Separator', 'on', ...
        'CData', tsgqc.readIcon('outils.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_CAL',...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', {@(src,evt) calOffMenuCallback(obj,src)},...
        'OnCallback',  {@(src,evt) calOnMenuCallback(obj,src)});
      
      obj.hdlInterpToggletool  =   uitoggletool(...   %
        'Parent',obj.hdlToolbar,...
        'TooltipString','Interpolate missing position',...
        'CData', tsgqc.readIcon('interp.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_INTERP',...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', {@(src,evt) interOffMenuCallback(obj,src)},...
        'OnCallback',  {@(src,evt) interOnMenuCallback(obj,src)});
      
      obj.hdlBottleToggletool  = uitoggletool(...   % Correction module toolbar button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Correct the SSS TSG data',...
        'CData', tsgqc.readIcon('bottleicon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_BOTTLE',...
        'UserData', 'off',...
        'Enable', 'off',...
        'OffCallback', {@(src,evt) bottleOffMenuCallback(obj,src)},...
        'OnCallback',  {@(src,evt) bottleOnMenuCallback(obj,src)});
      
      obj.hdlHeaderPushtool  = uipushtool(...   % Open headerForm button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Fill the header form',...
        'Separator', 'on', ...
        'CData', tsgqc.readIcon('hdricon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_HEADER',...
        'Enable', 'off',...
        'ClickedCallback', {@(src,evt) headerMenuCallback(obj,src)});
      
      obj.hdlReportPushtool  = uipushtool(...   % Open Report saving button
        'Parent',obj.hdlToolbar,...
        'TooltipString','Save a report',...
        'CData', tsgqc.readIcon('reporticon.mat'),...
        'HandleVisibility','on', ...
        'Tag','PUSHTOOL_REPORT',...
        'Enable', 'off',...
        'ClickedCallback', {@(src,evt) reportMenuCallback(obj,src)});
      
    end % end of setToolBarUI
   